### ISSUE TITLE
Elasticsearch cluster with Kibana

### ISSUE THREAD

**Issue by shigadeyo** [mapster/WeightyBeer#2]
Have you considered adding an option to use a Elasticsearch cluster with Kibana running locally rather than sending external to Google Firebase? Thanks!

**Comment by mapster** [comment]
I've certainly concidered replacing Firebase with something without the need for external communication, though I haven't gotten around to it. The only reason that I chose Firebase in the first place was that I wanted to learn about how it worked, and this was a great way to do that. Firebase has some great features which made it very easy to develop the web-client application. I might get around to it if I feel inspired some day, but I can't commit to it. Though I will probably choose something less heavy than elasticsearch, like CouchDB or MongoDB.

**Comment by mapster** [comment]
Firebase is replaced with a local redis database.
